name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GIT_HASH: $(git rev-parse --short "$GITHUB_SHA")

jobs:
      push-frontend-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './frontend'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Inventory Image'
            run: |
              docker build . --tag ghcr.io/Qt1RCC/sample-node-app-front:$GIT_HASH
              docker push ghcr.io/Qt1RCC/sample-node-app-front:$GIT_HASH

      push-backend-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './backend'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Inventory Image'
            run: |
              docker build . --tag ghcr.io/Qt1RCC/sample-node-app-back:$GIT_HASH
              docker push ghcr.io/Qt1RCC/sample-node-app-back:$GIT_HASH