name: Build & Deploy Images to GHCR

on:
  push:
    branches:
      - main

env:
  GIT_HASH: $(git rev-parse --short "$GITHUB_SHA")

jobs:
      CI-Frontend:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './frontend'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: Gets semantic release info
            id: semantic_release_info
            uses: jossef/action-semantic-release-info@v2.1.0
            env:
              GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Frontend Image'
            run: |
              docker build . --tag ghcr.io/qt1rcc/sample-node-app-front:${{ steps.semantic_release_info.outputs.version }}
              
          - name: 'Push Frontend Image'
            run: |
              docker push ghcr.io/qt1rcc/sample-node-app-front:${{ steps.semantic_release_info.outputs.version }}
              
      CI-Backend:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './backend'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: Gets semantic release info
            id: semantic_release_info
            uses: jossef/action-semantic-release-info@v2.1.0
            env:
              GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Backend Image'
            run: |
              docker build . --tag ghcr.io/qt1rcc/sample-node-app-back:${{ steps.semantic_release_info.outputs.version }}
              
          - name: 'Push Backend Image'
            run: |
              docker push ghcr.io/qt1rcc/sample-node-app-back:${{ steps.semantic_release_info.outputs.version }}
              
      Trigger_chart_update:
        needs: [CI-Frontend, CI-Backend]
        runs-on: ubuntu-latest
        permissions:
          contents: read
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main
            
          - name: Gets semantic release info
            id: semantic_release_info
            uses: jossef/action-semantic-release-info@v2.1.0
            env:
              GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
              
          - name: Repository Dispatch
            uses: peter-evans/repository-dispatch@v2
            with:
              token: ${{ secrets.GITHUB_TOKEN }}
              repository: qt1rcc/helm-charts
              event-type: new-app-version
              client-payload: '{"ref": "version-${{ steps.semantic_release_info.outputs.version }}", "version": "${{ steps.semantic_release_info.outputs.version }}"}'
