name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GIT_HASH: $(git rev-parse --short "$GITHUB_SHA")

jobs:
      push-frontend-image:
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: Semantic Release
            uses: cycjimmy/semantic-release-action@v3
            id: semantic
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

          - name: 'Build Frontend Image'
            working-directory: './frontend'
            run: |
              docker build . --tag ghcr.io/qt1rcc/sample-node-app-front:${{ steps.semantic.outputs.new_release_version }}
              docker push ghcr.io/qt1rcc/sample-node-app-front:${{ steps.semantic.outputs.new_release_version }}

          - name: 'Build Backend Image'
            working-directory: './backend'
            run: |
              docker build . --tag ghcr.io/qt1rcc/sample-node-app-back:${{ steps.semantic.outputs.new_release_version }}
              docker push ghcr.io/qt1rcc/sample-node-app-back:${{ steps.semantic.outputs.new_release_version }}
