name: "[Build & Deploy] Sample Node APP - Frontend image to GHCR"

on:
  push:
    branches:
      - main
    paths:
      - frontend/**

jobs:
      CI-Frontend:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './frontend'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: Bump version and push tag
            id: version_bump
            uses: anothrNick/github-tag-action@1.61.0
            env:
              GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
              DEFAULT_BRANCH: main
              DEFAULT_BUMP: patch
              WITH_V: true

          - name: Set up QEMU
            if: steps.version_bump.outputs.new_tag != steps.version_bump.outputs.old_tag
            uses: docker/setup-qemu-action@v2

          - name: Set up Docker Buildx
            if: steps.version_bump.outputs.new_tag != steps.version_bump.outputs.old_tag
            uses: docker/setup-buildx-action@v2

          - name: 'Login to GitHub Container Registry'
            if: steps.version_bump.outputs.new_tag != steps.version_bump.outputs.old_tag
            uses: docker/login-action@v2
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: Extract metadata for the Docker image
            if: steps.version_bump.outputs.new_tag != steps.version_bump.outputs.old_tag
            id: meta
            uses: docker/metadata-action@v4
            with:
              images: ghcr.io/qt1rcc/sample-node-app-front
              tags: |
                # minimal
                type=semver,pattern={{version}}
                # use custom value instead of git tag
                type=semver,pattern={{version}},value=v1.0.0

          - name: Build and push
            if: steps.version_bump.outputs.new_tag != steps.version_bump.outputs.old_tag
            uses: docker/build-push-action@v4
            with:
              context: frontend
              push: true
              tags: ${{ steps.meta.outputs.tags }}

          - name: Invoke workflow in another repo with inputs for frontend
            if: steps.version_bump.outputs.new_tag != steps.version_bump.outputs.old_tag
            uses: benc-uk/workflow-dispatch@v1
            with:
              workflow: manifest_update.yml
              token: ${{ secrets.GH_TOKEN }}
              repo: qt1rcc/helm-charts
              ref: ${{ github.event.pull_request.head.ref }}
              inputs: '{"ref": "sample_node_app_frontend-${{ env.DOCKER_METADATA_OUTPUT_VERSION }}", "version": "${{ env.DOCKER_METADATA_OUTPUT_VERSION }}", "appName": "sample_node_app", "appComponent": "frontend"}'
